INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Afghanistan','أفغانستان');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Albania','ألبانيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Aland Islands','جزر آلاند' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Algeria','الجزائر' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'American Samoa','ساموا-الأمريكي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Andorra','أندورا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Angola','أنغولا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Anguilla','أنغويلا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Antarctica','أنتاركتيكا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Antigua and Barbuda','أنتيغوا وبربودا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Argentina','الأرجنتين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Armenia','أرمينيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Aruba','أروبه' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Australia','أستراليا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Austria','النمسا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Azerbaijan','أذربيجان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bahamas','الباهاماس' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bahrain','البحرين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bangladesh','بنغلاديش' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Barbados','بربادوس' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Belarus','روسيا البيضاء' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Belgium','بلجيكا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Belize','بيليز'  );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Benin','بنين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Saint Barthelemy','سان بارتيلمي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bermuda','جزر برمودا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bhutan','بوتان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bolivia','بوليفيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bosnia and Herzegovina','البوسنة و الهرسك' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Botswana','بوتسوانا'  );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bouvet Island','جزيرة بوفيه' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Brazil','البرازيل' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'British Indian Ocean Territory','إقليم المحيط الهندي البريطاني' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Brunei Darussalam','بروني' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Bulgaria','بلغاريا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Burkina Faso','بوركينا فاسو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Burundi','بوروندي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Cambodia','كمبوديا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Cameroon','كاميرون');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Canada','كندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Cape Verde','الرأس الأخضر' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Cayman Islands','جزر كايمان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Central African Republic','جمهورية أفريقيا الوسطى' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Chad','تشاد'  );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Chile','شيلي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'China','الصين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Christmas Island','جزيرة عيد الميلاد' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Cocos (Keeling) Islands','جزر كوكوس' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Colombia','كولومبيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Comoros','جزر القمر'  );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Congo','الكونغو'  );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Cook Islands','جزر كوك' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Costa Rica','كوستاريكا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Croatia','كرواتيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Cuba','كوبا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Cyprus','قبرص' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Curaçao','كوراساو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Czech Republic','الجمهورية التشيكية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Denmark','الدانمارك' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Djibouti','جيبوتي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Dominica','دومينيكا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Dominican Republic','الجمهورية الدومينيكية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Ecuador','إكوادور' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Egypt','مصر' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'El Salvador','إلسلفادور' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Equatorial Guinea','غينيا الاستوائي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Eritrea','إريتريا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Estonia','استونيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Ethiopia','أثيوبيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Falkland Islands (Malvinas)','جزر فوكلاند' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Faroe Islands','جزر فارو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Fiji','فيجي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Finland','فنلندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'France','فرنسا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'French Guiana','غويانا الفرنسية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'French Polynesia','بولينيزيا الفرنسية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'French Southern and Antarctic Lands','أراض فرنسية جنوبية وأنتارتيكية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Gabon','الغابون' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Gambia','غامبيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Georgia','جيورجيا');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Germany','ألمانيا');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Ghana','غانا');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Gibraltar','جبل طارق' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Guernsey','غيرنزي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Greece','اليونان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Greenland','جرينلاند' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Grenada','غرينادا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Guadeloupe','جزر جوادلوب' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Guam','جوام' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Guatemala','غواتيمال' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Guinea','غينيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Guinea-Bissau','غينيا-بيساو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Guyana','غيانا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Haiti','هايتي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Heard and Mc Donald Islands','جزيرة هيرد وجزر ماكدونالد' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Honduras','هندوراس' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Hong Kong','هونغ كونغ' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Hungary','المجر' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Iceland','آيسلندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'India','الهند' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Isle of Man','جزيرة مان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Indonesia','أندونيسيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Iran','إيران' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Iraq','العراق' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Ireland','إيرلندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Italy','إيطاليا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Ivory Coast','ساحل العاج' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Jersey','جيرزي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Jamaica','جمايكا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Japan','اليابان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Jordan','الأردن' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Kazakhstan','كازاخستان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Kenya','كينيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Kiribati','كيريباتي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Korea(North Korea)','كوريا الشمالية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Korea(South Korea)','كوريا الجنوبية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Kosovo','كوسوفو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Kuwait','الكويت' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Kyrgyzstan','قيرغيزستان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Lao PDR','لاوس') ;
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Latvia','لاتفيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Lebanon','لبنان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Lesotho','ليسوتو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Liberia','ليبيريا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Libya','ليبيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Liechtenstein','ليختنشتين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Lithuania','لتوانيا');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Luxembourg','لوكسمبورغ' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Sri Lanka','سريلانكا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Macau','ماكاو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Macedonia','مقدونيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Madagascar','مدغشقر' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Malawi','مالاوي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Malaysia','ماليزيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Maldives','المالديف' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Mali','مالي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Malta','مالطا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Marshall Islands','جزر مارشال' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Martinique','مارتينيك' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Mauritania','موريتانيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Mauritius','موريشيوس' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Mayotte','مايوت');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Mexico','المكسيك' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Micronesia','مايكرونيزيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Moldova','مولدافيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Monaco','موناكو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Mongolia','منغوليا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Montenegro','الجبل الأسود' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Montserrat','مونتسيرات' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Morocco','المغرب' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Mozambique','موزمبيق' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Myanmar','ميانمار' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Namibia','ناميبيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Nauru','نورو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Nepal','نيبال' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Netherlands','هولندا');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Netherlands Antilles','جزر الأنتيل الهولندي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'New Caledonia','كاليدونيا الجديدة' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'New Zealand','نيوزيلندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Nicaragua','نيكاراجوا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Niger','النيجر' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Nigeria','نيجيريا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Niue','ني' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Norfolk Island','جزيرة نورفولك');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Northern Mariana Islands','جزر ماريانا الشمالية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Norway','النرويج' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Oman','عمان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Pakistan','باكستان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Palau','بالاو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Palestine','فلسطين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Panama','بنما' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Papua New Guinea','بابوا غينيا الجديدة'  );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Paraguay','باراغواي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Peru','بيرو');
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Philippines','الفليبين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Pitcairn','بيتكيرن' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Poland','بولندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Portugal','البرتغال' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Puerto Rico','بورتو ريكو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Qatar','قطر' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Reunion Island','ريونيون' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Romania','رومانيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Russian','روسيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Rwanda','رواندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Saint Kitts and Nevis','سانت كيتس ونيفس,' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Saint Martin (French part)','ساينت مارتن فرنسي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Sint Maarten (Dutch part)','ساينت مارتن هولندي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Saint Pierre and Miquelon','سان بيير وميكلون' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Saint Vincent and the Grenadines','سانت فنسنت وجزر غرينادين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Samoa','ساموا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'San Marino','سان مارينو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Sao Tome and Principe','ساو تومي وبرينسيبي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Saudi Arabia','المملكة العربية السعودية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Senegal','السنغال' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Serbia','صربيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Seychelles','سيشيل' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Sierra Leone','سيراليون' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Singapore','سنغافورة' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Slovakia','سلوفاكيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Slovenia','سلوفينيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Solomon Islands','جزر سليمان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Somalia','الصومال' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'South Africa','جنوب أفريقيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'South Georgia and the South Sandwich','المنطقة القطبية الجنوبية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'South Sudan','السودان الجنوبي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Spain','إسبانيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Saint Helena','سانت هيلانة' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Sudan','السودان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Suriname','سورينام' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Svalbard and Jan Mayen','سفالبارد ويان ماين' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Swaziland','سوازيلند' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Sweden','السويد' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Switzerland','سويسرا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Syria','سوريا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Taiwan','تايوان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Tajikistan','طاجيكستان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Tanzania','تنزانيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Thailand','تايلندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Timor-Leste','تيمور الشرقية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Togo','توغو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Tokelau','توكيلاو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Tonga','تونغا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Trinidad and Tobago','ترينيداد وتوباغو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Tunisia','تونس' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Turkey','تركيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Turkmenistan','تركمانستان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Turks and Caicos Islands','جزر توركس وكايكوس' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Tuvalu','توفالو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Uganda','أوغندا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Ukraine','أوكرانيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'United Arab Emirates','الإمارات العربية المتحدة' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'United Kingdom','المملكة المتحدة' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'United States','الولايات المتحدة' );
 INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Uruguay','أورغواي') ;
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Uzbekistan','أوزباكستان' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Vanuatu','فانواتو' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Venezuela','فنزويلا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Vietnam','فيتنام' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Virgin Islands (U.S.)','الجزر العذراء الأمريكي' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Vatican City','فنزويلا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Wallis and Futuna Islands','والس وفوتونا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Western Sahara','الصحراء الغربية' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Yemen','اليمن' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Zambia','زامبيا' );
INSERT INTO `countries` ( `name_ar`, `name_en`) VALUES ( 'Zimbabwe','زمبابوي');
